### ISSUE TITLE
Input data format

### ISSUE THREAD

**Issue by lijing-lin** [ShawnLYU/Quantile_Normalize#2]
It says in the 'Readme' file:

> Input data is a Pandas dataframe (df). Each row stands for an observations and each column stands for an attribute

Not sure if I got it right with what you meant by 'observations' and 'attribute'. According to [Quantile Normalization](https://en.wikipedia.org/wiki/Quantile_normalization), in the case of gene expression data, your codes are actually fit for input with each row being a gene (attribute?) and each column being a sample (observation?).

**Comment by coderfreestyle** [comment]
Firstly thanks for your question!

In this space, by 'observation' I meant the data that we are studying, while by 'attribute' I meant the features for each data.

Let me put it in this way, in this space, each row would be standing for one single data point, where its coordinates would be the columns, say it's a 100 dimensional space when there are 100 columns. What this function does is to normalise coordinates along each dimensions.

I have to admit that 'observations' and 'attributes' are quite misleading in different fields. Hope this would clarify a little bit.

**Comment by lijing-lin** [comment]
Ok. It is clear now. Basically, the code is to "normalise coordinates along each dimensions."
